#!/usr/bin/env bash
# setup-browser.sh — make the browser lane runnable without a system Chrome and
# without root.
#
# The lane (`playwright.config.ts`) drives Playwright's **managed** Chromium, so
# the browser is pinned by the `playwright` version in `pnpm-lock.yaml` rather
# than by whatever Chrome happens to be installed. This script:
#   1. installs that Chromium into a checkout-relative, persistent directory;
#   2. on Debian without root, stages the shared libraries its build needs (a
#      slim base image may not have them) into the same directory;
#   3. writes `.browser-env.sh`, which `scripts/with-browser-env.sh` sources
#      before running the browser lane or the screenshot script.
#
# Idempotent: re-running is a no-op once the browser and its libraries are in
# place. Override the location with `ORION_BROWSER_HOME`.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BROWSER_HOME="${ORION_BROWSER_HOME:-$(cd "$ROOT/.." && pwd)/.opencode/browser}"
BROWSERS_DIR="$BROWSER_HOME/ms-playwright"
LIBS_DIR="$BROWSER_HOME/libs"

# The Debian packages that provide the shared objects Chromium's Linux build
# links against. Names follow Debian 13 (trixie); `apt-cache depends --recurse`
# below pulls their transitive dependencies too.
PACKAGES=(
  libnspr4 libnss3 libatk1.0-0t64 libatk-bridge2.0-0t64 libatspi2.0-0t64
  libcups2t64 libdbus-1-3 libgbm1 libxkbcommon0 libxcomposite1 libxdamage1
  libxfixes3 libxrandr2 libasound2t64
)

echo "==> installing Playwright-managed Chromium into $BROWSERS_DIR"
PLAYWRIGHT_BROWSERS_PATH="$BROWSERS_DIR" pnpm exec playwright install chromium

CHROME="$(find "$BROWSERS_DIR" -type f -path '*/chrome-linux64/chrome' | sort | tail -1)"
if [[ -z "$CHROME" ]]; then
  echo "setup-browser: managed Chromium not found under $BROWSERS_DIR" >&2
  exit 1
fi

missing_libs() {
  ldd "$CHROME" 2>/dev/null | grep -c "not found" || true
}

LD_PATH="$LIBS_DIR/usr/lib/x86_64-linux-gnu:$LIBS_DIR/lib/x86_64-linux-gnu"
already_staged() {
  [[ "$(LD_LIBRARY_PATH="$LD_PATH" ldd "$CHROME" 2>/dev/null | grep -c 'not found' || true)" -eq 0 ]]
}

if [[ "$(missing_libs)" -gt 0 ]] && ! already_staged; then
  echo "==> staging Chromium's shared libraries into $LIBS_DIR (no root)"
  if ! command -v apt-get >/dev/null || ! command -v dpkg-deb >/dev/null; then
    echo "setup-browser: Chromium needs libraries this box lacks, and apt-get/dpkg-deb" >&2
    echo "  are unavailable. Install the Chromium dependencies, then re-run." >&2
    exit 1
  fi

  APT_STATE="$BROWSER_HOME/apt"
  DEBS_DIR="$BROWSER_HOME/debs"
  mkdir -p "$APT_STATE/lists/partial" "$APT_STATE/cache/archives/partial" \
    "$LIBS_DIR" "$DEBS_DIR"
  APT_OPTS=(
    -o "Dir::State::lists=$APT_STATE/lists"
    -o "Dir::Cache=$APT_STATE/cache"
    -o "Dir::State::status=/var/lib/dpkg/status"
    -o "APT::Sandbox::User=root"
  )
  apt-get "${APT_OPTS[@]}" update >/dev/null

  mapfile -t ALL < <(apt-cache "${APT_OPTS[@]}" depends --recurse \
    --no-recommends --no-suggests --no-conflicts --no-breaks \
    --no-replaces --no-enhances "${PACKAGES[@]}" 2>/dev/null \
    | grep -E '^[a-z0-9]' | awk '{print $1}' | sort -u)
  if [[ "${#ALL[@]}" -eq 0 ]]; then
    echo "setup-browser: apt-cache returned no packages to download" >&2
    exit 1
  fi
  (cd "$DEBS_DIR" && apt-get "${APT_OPTS[@]}" download "${ALL[@]}" >/dev/null)
  for deb in "$DEBS_DIR"/*.deb; do dpkg-deb -x "$deb" "$LIBS_DIR"; done
  rm -rf "$DEBS_DIR" "$APT_STATE"
fi

cat >"$ROOT/.browser-env.sh" <<EOF
# Generated by scripts/setup-browser.sh — machine-local, gitignored.
export PLAYWRIGHT_BROWSERS_PATH="$BROWSERS_DIR"
export LD_LIBRARY_PATH="$LD_PATH\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}"
EOF

echo "==> wrote $ROOT/.browser-env.sh"
echo "    Chromium: $CHROME"
echo "    missing libraries after setup: $(LD_LIBRARY_PATH="$LD_PATH" ldd "$CHROME" 2>/dev/null | grep -c 'not found' || true)"
